### ISSUE TITLE
upload image easier discoverability

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2-studio-issue-tracker#28]
currently quite hard to discover. perhaps it should be accessible in console

<img width="613" alt="Screen Shot 2023-09-19 at 11 07 32 AM" src="https://github.com/terrastruct/d2-studio-issue-tracker/assets/3120367/ef5a8604-e20f-4871-9d7f-d3e69afeff21">

**Comment by gavin-ts** [comment]
I think adding the images button next to the gear would be a good place since it is right next to where you would use it (example below) 
<img width="210" alt="Screenshot 2023-10-18 at 11 58 56 AM" src="https://github.com/terrastruct/d2-studio-issue-tracker/assets/85081687/96c540ca-214a-4294-b07e-7cb8a706a75b">

Adding a manage images section in the console also sounds appropriate for organization purposes.

**Comment by alixander** [comment]
@gavin-ts I think as soon as you click it, you lose your cursor position though.

**Comment by gavin-ts** [comment]
> @gavin-ts I think as soon as you click it, you lose your cursor position though.

I think we can just save it, or maybe it can work where you click to insert after selecting the image. I think simply saving where the cursor was before opening makes the most sense (it's the same as using command I)

**Comment by alixander** [comment]
Hmmm true, I'm for it
